# Render.yaml

name: go-activity-tracking-api
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activity_tracking
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306
  go-server:
    build: .
    dockerfile: Dockerfile
    ports:
      - 8080
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=activity_tracking
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    depends_on:
      - mysql
